# Generated by Django 3.2.24 on 2024-02-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name']},
        ),
        migrations.AlterField(
            model_name='company',
            name='internal_notes',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
